import { HierarchyNode } from "d3";
import { SunburstItem } from "../../../sunburstLibrary";
import { AbstractHierarchy } from "../AbstractHierarchy";
import { TreeNode, createTree } from "../../Tree";

/**
 * Concrete implementation of AbstractHierarchy class
 * Segments are generated by splitting `name` by '.' characters
 * Item value is size property for summing and sorting methods
 */
export class FlatDataHierarchy extends AbstractHierarchy<SunburstItem> {
    constructor() {
        super();
    }
    private static _getSegmentIterator(item: SunburstItem) {
        return item.name.split('.').values();
    }
    private static _nodeValue(d: TreeNode<SunburstItem>): number | undefined {
        return d.data?.size ?? 0
    }
    createTree(items: SunburstItem[]): TreeNode<SunburstItem> {
        return createTree({ items, getSegmentIterator: FlatDataHierarchy._getSegmentIterator });
    }
    sum(d: TreeNode<SunburstItem>): number {
        return FlatDataHierarchy._nodeValue(d)
    }
    sort(a: HierarchyNode<TreeNode<SunburstItem>>, b: HierarchyNode<TreeNode<SunburstItem>>): number {
        return FlatDataHierarchy._nodeValue(a) - FlatDataHierarchy._nodeValue(b);
    }
    getChildren(d: TreeNode<SunburstItem>): IterableIterator<TreeNode<SunburstItem>> | null | undefined {
        return d.children;
    }
}
